import os
from pathlib import Path
from typing import Dict, Any
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

class ReportGenerator:
    def __init__(self):
        self.reports_dir = Path("/app/backend/reports")
        self.reports_dir.mkdir(exist_ok=True)
    
    async def generate_pdf(self, scan_data: Dict) -> str:
        """Generate PDF report"""
        try:
            from weasyprint import HTML, CSS
            
            html_content = await self.generate_html(scan_data)
            
            report_filename = f"report_{scan_data['id']}.pdf"
            report_path = self.reports_dir / report_filename
            
            HTML(string=html_content).write_pdf(
                report_path,
                stylesheets=[CSS(string=self._get_pdf_styles())]
            )
            
            return str(report_path)
        
        except Exception as e:
            logger.error(f"PDF generation failed: {str(e)}")
            raise
    
    async def generate_html(self, scan_data: Dict) -> str:
        """Generate HTML report"""
        vulnerabilities = scan_data.get('vulnerabilities', [])
        
        severity_counts = {
            'Critical': sum(1 for v in vulnerabilities if v.get('severity') == 'Critical'),
            'High': sum(1 for v in vulnerabilities if v.get('severity') == 'High'),
            'Medium': sum(1 for v in vulnerabilities if v.get('severity') == 'Medium'),
            'Low': sum(1 for v in vulnerabilities if v.get('severity') == 'Low')
        }
        
        vuln_html = ""
        for vuln in vulnerabilities:
            vuln_html += f"""
            <div class="vulnerability {vuln.get('severity', 'Low').lower()}">
                <h3>{vuln.get('type', 'Unknown')}</h3>
                <p><strong>Endpoint:</strong> {vuln.get('endpoint', 'N/A')}</p>
                <p><strong>Severity:</strong> <span class="badge {vuln.get('severity', 'Low').lower()}">{vuln.get('severity', 'Low')}</span></p>
                <p><strong>Description:</strong> {vuln.get('description', 'No description')}</p>
                <p><strong>Evidence:</strong> {vuln.get('evidence', 'No evidence')}</p>
                <p><strong>Mitigation:</strong> {vuln.get('mitigation', 'No mitigation')}</p>
            </div>
            """
        
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>WebScanPro Security Report</title>
            <style>{self._get_html_styles()}</style>
        </head>
        <body>
            <div class="header">
                <h1>WebScanPro Security Assessment Report</h1>
                <p class="subtitle">Automated Vulnerability Scan Results</p>
            </div>
            
            <div class="executive-summary">
                <h2>Executive Summary</h2>
                <p><strong>Target:</strong> {scan_data.get('target_url', 'N/A')}</p>
                <p><strong>Scan Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                <p><strong>Total Vulnerabilities:</strong> {len(vulnerabilities)}</p>
                
                <div class="severity-summary">
                    <div class="severity-box critical">
                        <div class="count">{severity_counts['Critical']}</div>
                        <div class="label">Critical</div>
                    </div>
                    <div class="severity-box high">
                        <div class="count">{severity_counts['High']}</div>
                        <div class="label">High</div>
                    </div>
                    <div class="severity-box medium">
                        <div class="count">{severity_counts['Medium']}</div>
                        <div class="label">Medium</div>
                    </div>
                    <div class="severity-box low">
                        <div class="count">{severity_counts['Low']}</div>
                        <div class="label">Low</div>
                    </div>
                </div>
            </div>
            
            <div class="vulnerabilities">
                <h2>Detailed Findings</h2>
                {vuln_html if vuln_html else '<p>No vulnerabilities detected.</p>'}
            </div>
            
            <div class="footer">
                <p>Generated by WebScanPro - Automated Security Scanner</p>
                <p>This report is confidential and intended for authorized personnel only.</p>
            </div>
        </body>
        </html>
        """
        
        return html
    
    def _get_html_styles(self) -> str:
        return """
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
            border-radius: 8px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 2.5em;
        }
        .subtitle {
            font-size: 1.2em;
            opacity: 0.9;
        }
        .executive-summary {
            background: white;
            padding: 30px;
            border-radius: 8px;
            margin-bottom: 30px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .severity-summary {
            display: flex;
            gap: 20px;
            margin-top: 20px;
        }
        .severity-box {
            flex: 1;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            color: white;
        }
        .severity-box.critical { background: #ef4444; }
        .severity-box.high { background: #f97316; }
        .severity-box.medium { background: #eab308; }
        .severity-box.low { background: #3b82f6; }
        .severity-box .count {
            font-size: 3em;
            font-weight: bold;
        }
        .severity-box .label {
            font-size: 1.2em;
            margin-top: 10px;
        }
        .vulnerabilities {
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .vulnerability {
            padding: 20px;
            margin: 20px 0;
            border-left: 4px solid #ddd;
            background: #f9f9f9;
            border-radius: 4px;
        }
        .vulnerability.critical { border-left-color: #ef4444; }
        .vulnerability.high { border-left-color: #f97316; }
        .vulnerability.medium { border-left-color: #eab308; }
        .vulnerability.low { border-left-color: #3b82f6; }
        .vulnerability h3 {
            margin-top: 0;
            color: #333;
        }
        .badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 12px;
            font-weight: bold;
            font-size: 0.9em;
        }
        .badge.critical { background: #fee2e2; color: #991b1b; }
        .badge.high { background: #ffedd5; color: #9a3412; }
        .badge.medium { background: #fef9c3; color: #854d0e; }
        .badge.low { background: #dbeafe; color: #1e40af; }
        .footer {
            text-align: center;
            margin-top: 40px;
            padding: 20px;
            color: #666;
            font-size: 0.9em;
        }
        """
    
    def _get_pdf_styles(self) -> str:
        return self._get_html_styles()